### ISSUE TITLE
Update UI Kit Topics

### ISSUE THREAD

**Issue by StefanIvanov** [IgniteUI/indigo-design-docfx#332]
Update documentation including screenshots to reflect the new version of the UI Kit for Sketch

Covers: 

[USING THE DESIGN SYSTEM>Components](https://www.infragistics.com/products/indigo-design/help/components/components.html)

- [x] Create introductory general [Components](https://www.infragistics.com/products/indigo-design/help/components/components-overview.html) topic @StefanIvanov 
- [x] Create introductory general [Patterns](https://www.infragistics.com/products/indigo-design/help/patterns/patterns-overview.html) topic @StefanIvanov 
- [x] [Getting Started](https://www.infragistics.com/products/indigo-design/help/getting-started.html) @StefanIvanov 
- [x] [Creating Your First Artboard](https://www.infragistics.com/products/indigo-design/help/creating-an-artboard.html) @YoannaIvanova 
---------------------------------------------
- [x] [Overview](https://www.infragistics.com/products/indigo-design/help/style/styling-overview.html) @StefanIvanov 
- [x] [Colors](https://www.infragistics.com/products/indigo-design/help/style/colors.html) @StefanIvanov 
- [x] [Elevation](https://www.infragistics.com/products/indigo-design/help/style/elevation.html) @StefanIvanov 
- [x] [Material Icons](https://www.infragistics.com/products/indigo-design/help/style/material-icons.html) @StefanIvanov 
- [x] [Typography](https://www.infragistics.com/products/indigo-design/help/style/typography.html) @StefanIvanov 
- [x] [Illustrations](https://www.infragistics.com/products/indigo-design/help/style/illustrations.html) @StefanIvanov 
---------------------------------------------
- [x] [Avatar](https://www.infragistics.com/products/indigo-design/help/components/avatar.html) @YoannaIvanova 
- [x] [Badge](https://www.infragistics.com/products/indigo-design/help/components/badge.html) @YoannaIvanova 
- [x] [Bottom Navigation](https://www.infragistics.com/products/indigo-design/help/components/bottom-nav.html) @StefanIvanov 
- [x] [Button Group](https://www.infragistics.com/products/indigo-design/help/components/button-group.html) @StefanIvanov 
- [x] [Button](https://www.infragistics.com/products/indigo-design/help/components/button.html) @StefanIvanov 
- [x] [Calendar](https://www.infragistics.com/products/indigo-design/help/components/calendar.html) @StefanIvanov
- [x] [Carousel](https://www.infragistics.com/products/indigo-design/help/components/carousel.html) @YoannaIvanova 
- [x] [Cards](https://www.infragistics.com/products/indigo-design/help/components/cards) and also remove the Custom Card topic from ToC @StefanIvanov 
- [x] Charts new heading with 4 topics - one for each of the 4 chart types we currently have @tosharky 
- [x] Gauges new heading with 
  - [x] [Bullet Graph](https://www.infragistics.com/products/indigo-design/help/components/bullet-graph.html) @tosharky 
  - [x] [Linear Gauge](https://www.infragistics.com/products/indigo-design/help/components/linear-gauge.html) @tosharky 
  - [x] [Radial Gauge](https://www.infragistics.com/products/indigo-design/help/components/radial-gauge.html) @tosharky 
- [x] [Checkbox](https://www.infragistics.com/products/indigo-design/help/components/checkbox.html) @YoannaIvanova 
- [x] [Chip and Chips Area](https://www.infragistics.com/products/indigo-design/help/components/checkbox.html) @YoannaIvanova 
- [x] [Combo](https://www.infragistics.com/products/indigo-design/help/components/combo.html) @YoannaIvanova 
- [x] Date picker new topic @StefanIvanov
- [x] [Dialog](https://www.infragistics.com/products/indigo-design/help/components/dialog.html) @YoannaIvanova 
- [x] [Dropdown](https://www.infragistics.com/products/indigo-design/help/components/dropdown.html) @YoannaIvanova 
- [x] [Grid](https://www.infragistics.com/products/indigo-design/help/components/grid.html) and all its subtopics @YoannaIvanova
- [x] [Grid Skeleton] add new topic @YoannaIvanova
- [x] [Hyperlink](https://www.infragistics.com/products/indigo-design/help/components/hyperlink.html) @YoannaIvanova 
- [x] [Hierarchical grid](https://www.infragistics.com/products/indigo-design/help/components/hierarchical-grid.html)
- [x] - [ ] [Hierarchical grid Skeleton] add new topic
- [x] [Icon](https://www.infragistics.com/products/indigo-design/help/components/icon.html) @YoannaIvanova 
- [x] [Input](https://www.infragistics.com/products/indigo-design/help/components/input.html) @YoannaIvanova 
- [x] [List](https://www.infragistics.com/products/indigo-design/help/components/list.html) @YoannaIvanova 
- [x] [List Skeleton] add new topic @YoannaIvanova 
- [x] [Navbar](https://www.infragistics.com/products/indigo-design/help/components/navbar.html) @YoannaIvanova 
- [x] [Navigation Drawer](https://www.infragistics.com/products/indigo-design/help/components/nav-drawer.html) @YoannaIvanova 
- [x] [Progress bar](https://www.infragistics.com/products/indigo-design/help/components/progress.html) @YoannaIvanova 
- [x] [Radio Group](https://www.infragistics.com/products/indigo-design/help/components/radio-group.html) @YoannaIvanova 
- [x] [Slider](https://www.infragistics.com/products/indigo-design/help/components/slider.html) @YoannaIvanova 
- [x] [Snackbar](https://www.infragistics.com/products/indigo-design/help/components/snackbar.html) @YoannaIvanova 
- [x] [Switch](https://www.infragistics.com/products/indigo-design/help/components/switch.html) @YoannaIvanova 
- [x] [Tabs](https://www.infragistics.com/products/indigo-design/help/components/tabs.html) @YoannaIvanova 
- [x] [Time Picker](https://www.infragistics.com/products/indigo-design/help/components/time-picker.html) @StefanIvanov
- [x] [Toast](https://www.infragistics.com/products/indigo-design/help/components/toast.html) @YoannaIvanova 
- [x] [Tooltip](https://www.infragistics.com/products/indigo-design/help/components/tooltip.html) @YoannaIvanova 
- [x] [Tree Grid](https://www.infragistics.com/products/indigo-design/help/components/tree-grid.html)
- [x] [Tree grid Skeleton] add new topic
---------------------------------------------
Patterns
- [x] AV Player @sdimchevski 
- [x] Avatar + Badge @sdimchevski 
- [x] Bar @sdimchevski 
- [x] **new topic** Chat @YoannaIvanova 
- [x] Checkbox group @sdimchevski 
- [x] Data Visualizations @sdimchevski 
- [x] Details @sdimchevski 
- [x] **new topic** Dialogs @sdimchevski 
- [x] **new topic** Empty States @sdimchevski 
- [x] File Upload @sdimchevski 
- [x] Footer @YoannaIvanova 
- [x] Form @sdimchevski 
- [x] Grid @sdimchevski 
- [x] Hierarchical grid @sdimchevski 
- [x] Image Manipulation @sdimchevski 
- [x] Lists @sdimchevski 
- [x] Menus @sdimchevski 
- [x] Onboarding @sdimchevski 
- [x] Pricing table @sdimchevski 
- [x] Scheduling @YoannaIvanova 
- [x] **new topic** Social Feed @YoannaIvanova 
- [x] Tiles @sdimchevski 
- [x] Tree grid @sdimchevski 
- [x] User Profile @sdimchevski
