### ISSUE TITLE
Update the APP BUILDER OVERVIEW section

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/indigo-design-docfx#344]
Update documentation including screenshots to reflect the new version of the APP BUILDER OVERVIEW

Covers: 

[APP BUILDER OVERVIEW](https://staging.infragistics.com/products/indigo-design/help/appbuilder/app-builder-overview.html)

- [ ] Create introductory general [APP BUILDER OVERVIEW](https://staging.infragistics.com/products/indigo-design/help/appbuilder/app-builder-overview.html) @kdinev - https://github.com/IgniteUI/indigo-design-docfx/issues/350
- [ ] [Getting started](https://staging.infragistics.com/products/indigo-design/help/appbuilder/getting-started.html) @DaniMarinov @radomirchev - https://github.com/IgniteUI/indigo-design-docfx/issues/351  
- [ ] [Interface Overview](https://staging.infragistics.com/products/indigo-design/help/appbuilder/interface-overview.html) @DaniMarinov - https://github.com/IgniteUI/indigo-design-docfx/issues/352
- [ ] [Flex layouts](https://staging.infragistics.com/products/indigo-design/help/appbuilder/flex-layouts.html) - https://github.com/IgniteUI/indigo-design-docfx/issues/353
  - [ ] [Row and column layout](https://staging.infragistics.com/products/indigo-design/help/appbuilder/flex-layouts/row-and-column-layout.html) - https://github.com/IgniteUI/indigo-design-docfx/issues/354
  - [ ] [Fluid resizing & wrapping](https://staging.infragistics.com/products/indigo-design/help/appbuilder/flex-layouts/fluid-resizing-%26-wrapping.html) - https://github.com/IgniteUI/indigo-design-docfx/issues/355
  - [ ] [Add to layout via context menu](https://staging.infragistics.com/products/indigo-design/help/appbuilder/flex-layouts/add-to-layout-via-context-menu.html) - https://github.com/IgniteUI/indigo-design-docfx/issues/356
  - [ ] [Additional resources to learn about web-layouts](https://staging.infragistics.com/products/indigo-design/help/appbuilder/flex-layouts/additional-resources-to-learn-about-web-layouts.html) - https://github.com/IgniteUI/indigo-design-docfx/issues/357
- [ ] [Indigo.Design App Builder components](https://staging.infragistics.com/products/indigo-design/help/appbuilder/indigo.design-app-builder-components.html) @DaniMarinov - https://github.com/IgniteUI/indigo-design-docfx/issues/358
  - [ ] [Quick add components](https://staging.infragistics.com/products/indigo-design/help/appbuilder/indigo-design-components/quick-add-components.html) - https://github.com/IgniteUI/indigo-design-docfx/issues/359 
  - [ ] [Configuring components](https://staging.infragistics.com/products/indigo-design/help/appbuilder/indigo-design-components/configuring-components.html) - https://github.com/IgniteUI/indigo-design-docfx/issues/360
- [ ] [App themes](https://staging.infragistics.com/products/indigo-design/help/appbuilder/app-themes.html) - https://github.com/IgniteUI/indigo-design-docfx/issues/361
  - [ ] [Switching app themes](https://staging.infragistics.com/products/indigo-design/help/appbuilder/app-themes/switching-app-themes.html) - https://github.com/IgniteUI/indigo-design-docfx/issues/362
  - [ ] [Material vs. Fluent vs Bootstrap](https://staging.infragistics.com/products/indigo-design/help/appbuilder/app-themes/material-vs-fluent-vs-bootstrap.html) - https://github.com/IgniteUI/indigo-design-docfx/issues/363
  - [ ] [Customize & apply theme](https://staging.infragistics.com/products/indigo-design/help/appbuilder/app-themes/customize-%26-apply-theme.html) - https://github.com/IgniteUI/indigo-design-docfx/issues/364
- [ ] [Single page apps and navigation](https://staging.infragistics.com/products/indigo-design/help/appbuilder/single-page-apps-and-navigation.html) - https://github.com/IgniteUI/indigo-design-docfx/issues/365
  - [ ] [Master view vs. Child views](https://staging.infragistics.com/products/indigo-design/help/appbuilder/spa-and-navigation/master-view-vs-child-views.html) - https://github.com/IgniteUI/indigo-design-docfx/issues/366
  - [ ] [Add navigations (routing)](https://staging.infragistics.com/products/indigo-design/help/appbuilder/spa-and-navigation/add-navigations-(routing).html) - https://github.com/IgniteUI/indigo-design-docfx/issues/367
- [ ] [Using Data in Your App ](https://staging.infragistics.com/products/indigo-design/help/appbuilder/using-data-in-your-app.html) - https://github.com/IgniteUI/indigo-design-docfx/issues/373

To be updated

**Comment by StefanIvanov** [comment]
@radomirchev I think you can close this one, it seems like it has been long resolved
