### ISSUE TITLE
Update the CODE GENERATION section

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/indigo-design-docfx#345]
Update documentation including screenshots to reflect the new version of the CODE GENERATION

Covers: 

[VS CODE GENERATION](https://www.infragistics.com/products/indigo-design/help/codegen/installing-vs-code-extension.html)
- [ ] Update [Installing the Visual Code Extension](https://www.infragistics.com/products/indigo-design/help/codegen/installing-vs-code-extension.html) @ChronosSF - https://github.com/IgniteUI/indigo-design-docfx/issues/346
- [ ] Update [Using the Code Generator Plugin](https://www.infragistics.com/products/indigo-design/help/codegen/vscode-plugin.html) @ChronosSF - https://github.com/IgniteUI/indigo-design-docfx/issues/347
- [ ] Update [After code generation](https://www.infragistics.com/products/indigo-design/help/codegen/after-codegen.html) @Lipata - https://github.com/IgniteUI/indigo-design-docfx/issues/348
- [ ] Update [Layout Generation](https://www.infragistics.com/products/indigo-design/help/codegen/layout-codegen.html) @ig-georgeA - https://github.com/IgniteUI/indigo-design-docfx/issues/349

**Comment by zdrawku** [comment]
First two points are not relevant anymore as we do not have the VS plugin
The second two points are marked as duplicate from Stefan Ivanov some time ago
