### ISSUE TITLE
Update UI Kit docs to account for Adobe XD support 

### ISSUE THREAD

**Issue by StefanIvanov** [IgniteUI/indigo-design-docfx#514]
- [x] Update the Creating Your First Prototype topic WORKFLOW-XD @StefanIvanov @tosharky 
- [x] Update the Creating Your First Artboard to be for Sketch @StefanIvanov 
- [x] Introduce a new topic for Creating Your First Artboard in Adobe XD @StefanIvanov 
- [x] Update the Responsive Layouts (Best Practices) topic GRINDERS @MayaKirova has just made a PR for this
----------------
- [x] From all patterns topics remove the warning for the necessity to detach @YoannaIvanova 
- [x] Update Styling Overview to have two sections introducing how things are in Adobe XD UI Kit @StefanIvanov 
- [x] Update the Colors topic to split Palette Generation and Creating Custom Colors into a Sketch and Adobe XD subsections @StefanIvanov 
- [x] Update the Elevations topic to include guidance for how elevations are used in Adobe XD @StefanIvanov 
- [x] Update the Material Icons topic with up-to-date numbers and categories and split the Adding Icons section into one section for Sketch and one for Adobe XD @StefanIvanov 
- [x] Update the Typography topic to include guidance for Adobe XD and split the Changing the Typeface and Creating Custom Typographies sections into sections for Sketch and for Adobe XD @StefanIvanov 
- [x] Update the Illustrations topic to also mention where they are in Adobe XD @StefanIvanov 
- [x] Update the Components Overview topic to also mention Adobe XD @YoannaIvanova 
- [x] Remove the second occurrence of Checkbox, Chip, and Combo topics from ToC
----------------
- [x] Update all components styling sections to not mention overrides but use something more generic instead e.g. options @YoannaIvanova 
- [x] Update all components that have states for the State feature of Adobe XD @YoannaIvanova 
- [x] Update all components that can set things to ~No Symbol to hide to have layers deleted in Adobe XD instead @YoannaIvanova 
- [x] Update all components that have content templates as overrides in Sketch to the approach show and delete unused layers in XD. Also mention dragging elements in the stack to change their order e.g. list item has many of its layers hidden from the item instance in the list component symbol @YoannaIvanova 
- [x] Update Components Overview topic, Creating an Artboard with Sketch topic and Creating an Artboard with XD topic to explain that symbols and components designated as  _Overrides must not be inserted on artboards as they provide components states and do not represent to complete component by itself @YoannaIvanova 
- [x] Update Components Overview topic and Patterns Overview topic to explain that no detaching is needed in Adobe XD @YoannaIvanova 
- [x] Update Grids and List so that the Detach from Symbol section is only applicable to Sketch and destroying the symbol is not necessary for Adobe XD @YoannaIvanova 
- [x] We may have to refactor the list item topic fully and in the custom list item mention that the suggestions are only applicable to Sketch as Adobe XD allows for richer templating without destroying the symbol **related to the one above** @YoannaIvanova 
- [x] Add Skeleton Charts topics @StefanIvanov 
- [x] Update the Radio Group to have horizontal and vertical stacks @StefanIvanov 
- [x] Remove badge shape variants as we currently have just one @StefanIvanov 
- [x] Add advanced filtering topic @StefanIvanov
