### ISSUE TITLE
Update UI Kit docs based on latest designs

### ISSUE THREAD

**Issue by YoannaIvanova** [IgniteUI/indigo-design-docfx#608]
- [x] Update "icons_add4" image in the Material Icons topic (section Adding Icons/In Sketch/4.) because in Fills, the color should be grays, not grays.700
- [x] Update the image in Adobe XD section in Components topic (contained button and FAB appear to be in hover state)
- [x] Edit the text in the Shape section of Avatar topic because the avatar comes in a circle form, not in a round form in the UI Kit
- [x] Add a State section in Badge topic (default, info, success, warn, error)
- [x] Update the images and the text about raised button in Button topic with contained button
- [x] Update all images in Calendar and Scheduler topics
- [x] Update the images with card actions in the Card and Skeleton Card topics (icons are button icons now, and there are slight changes in their size and position)
- [x] Update Chip and chips area topic with a Type section for default and primary type variant, add Interaction state section for enabled/disabled states, and add hover/selected/templated states in Chip State section
- [x] Update the images in the Dropdown Item States and Styling sections in the Combo topic
- [x] Update all images in Date Picker topic
- [x] Replace desktop and mobile types with display densities (comfortable, cosy, compact) in the Type section in Dropdown topic
- [x] Update the images in the Grid Excel Style Filter topic
- [x] Update the Navbar topic with icon actions and icon button actions variants
- [x] Update all images in the Slider topic
- [x] Update all images in the Snackbar topic (snackbar background is darker)
- [x] Update all images in the Switch topic
- [x] Update the images in the Picker Layout section and Usage section in the Time Picker topic. And mention the seconds' portion in the Content section
- [x] Update the images in the Toast Demo section, Position section, and Usage section in Toast topic (toast background is darker)
- [x] Update the image in the Patterns/Grid topic (because of paging design)
- [x] Update the image in the Patterns/Pricing Table topic. And edit href: "pricing-plan.md" to href: "pricing-table.md" in the toc file
- [x] Update the image in the Patterns/Tree Grid topic (because of paging design)
- [x] Update the first two images in Responsive layouts in Sketch topic (buttons should be contained, not raised)
- [x] Update the first two images in Responsive layouts in AdobeXD topic (buttons should be contained, not raised)
